version: '3.7'
services:
  app:
    image: lissonpsantos2/ubuntu-phps:latest
    restart: always
    networks:
      - opentelemetry_php
    container_name: opentelemetry_php_api
    volumes:
      - ./:/home/project-folder/
    command: bash -c "selectphp 8.1 && apachelinker /home/project-folder/public && tail -f /tmp/dev.log"
    ports:
      - 8101:80
networks:
  opentelemetry_php:
    name: opentelemetry_php
    driver: bridge